version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: hono-postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: manmade
      POSTGRES_PASSWORD: manmade
      POSTGRES_DB: fitdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: